name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: |
        make
        ./test

  macos-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: |
        make
        ./test
